kind: Product
apiVersion: api.webmethods.io/beta
metadata:
  name: productPublish
  namespace: PublishTesting
  version: '1.0'
  tags: []
  description: ''
spec:
  apis:
    - $ref: PublishTesting:DPAPI:1.0
  plans:
    - $ref: DPProject_Publish:NewPlanDP:1.0
