kind: GlobalPolicy
apiVersion: api.webmethods.io/beta
metadata:
  name: GlobalPolicy
  namespace: dev_global
  version: '1.0'
  tags: []
spec:
  filter-api-type:
    - REST
    - SOAP
    - ODATA
  filter-http-methods:
    - GET
    - PUT
    - POST
  filter-attributes: asdfasdf
  policy-sequence:
    - $ref: dev_cors:policyseq:1.0
