kind: GlobalPolicy
apiVersion: api.webmethods.io/beta
metadata:
  name: GlobalPolicy
  namespace: dev_global
  version: '1.0'
  tags: []
spec:
  filter-api-type:
    - REST
    - SOAP
  filter-http-methods:
    - GET
