#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: policyseq
  version: 1.0
  namespace: dev_cors
  tags:
    - seq
spec:
  transport:
    - $ref: dev_cors:transport:alpha
  routing:
    - $ref: dev_cors:routing:1.0