kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/beta
metadata:
  name: IAM_vcstest
  namespace: test
  version: '1.0'
  tags: []
spec:
  triggerPolicyViolation: true
  identificationType:
    or:
      apiKey:
        applicationLookup: default
      hostNameAddress:
        applicationLookup: registered
      httpBasicAuth:
        applicationLookup: registered
      ipAddressRange:
        applicationLookup: registered
