kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: test_endpoint
  namespace: dev
  version: alpha
  tags: []
spec:
  url: https://localhost:3000
  method: GET
  connectTimeout: 200
  readTimeout: 97
