kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: policyseq_mon
  version: '1.0'
  namespace: mon
  tags:
    - seq
spec:
  transport:
    - $ref: mon:transport:alpha
  routing:
    - $ref: mon:routing:1.0
  monitoring:
    - $ref: mon:log_invocation:1.0
    - $ref: mon:service_cache:1.0