kind: policySequence
apiVersion: api.webmethods.io/v1
metadata:
  name: dev_policies_nltm
  version: 1.0
  namespace: dev_123
  tags:
    - dev_policies
spec:
  transport:
    - $ref: dev:enable_https_nltm:1.0
  iam:
    - $ref: dev:identify_and_authorize_nltm:1.0
  routing:
    - $ref: dev:my-default-routing_nltm:1.0
    - $ref: sample:OutboundNTLMAuth:1.0