kind: api
apiVersion: api.webmethods.io/v1
metadata:
  name: Oubound_Anonymous_UI
  namespace: dev
  version: 1.0
  tags:
    - swagger
    - daso
    - sample
  type: REST
spec:
  api-spec:
    $path: petstore.yml
  policy-sequence: 
    - $ref: dev:dev_policies:1.0