#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: APIRouting_DevUI
  namespace: dev
  version: 1.0
  tags:
    - one
    - two
    - three
    - sample
  type: REST
spec:
  api-spec:
    $path: petstore.yaml
  policy-sequence:
    - $ref: dev:policyseq:1.0