kind: InboundBulkHead
apiVersion: api.ibm.com/v1
metadata:
  name: InboundBulkHead
  namespace: InboundBulkHead_Project
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  maxConcurrentCalls: 1
  enableBulkheadForCallbacks:
    maxConcurrentCallbacks: 3
