#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: api
apiVersion: api.webmethods.io/v1
metadata:
  name: MultiYaml
  namespace: dev
  version: 1.0
  tags:
    - swagger
    - multi
    - sample
  type: REST
spec:
  mocked: true
  api-spec: 
    $path: petstore.yaml
  policy-sequence: 
    - $ref: dev:dev_policies:1.0
 
---
kind: Transport
apiVersion: api.webmethods.io/v1
metadata:
  name: enable_https
  namespace: dev
  version: 1.0
spec: 
    protocol:
      - http
      - https
   
---
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: my-default-routing
  version: 1.0
  namespace: dev
  tags:
    - routing
    - route
    - policy
spec:
  default-endpoint:
    $ref: dev:default_endpoint:1.0
   
---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint
  version: 1.0
  namespace: dev
spec:
  url: http://test.com
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    truststoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""

---
kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: dev_policies
  version: 1.0
  namespace: dev
  tags:
    - seq
spec:
  transport:
    - $ref: dev:enable_https:1.0
  iam:
    - $ref: dev:My_IAM:1.0
  monitoring:
    - $ref: dev:log_invocation:1.0
  routing:
    - $ref: dev:my-default-routing:1.0
  req-processing:
    - $ref: dev:validate_API_Specification_policy:1.0
    - $ref: dev:request_processing_policy:1.0


---
kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/beta
metadata:
  name: My_IAM
  version: 1.0
  namespace: dev
  tags:
    - IAM
spec:
  enabled: true
  triggerPolicyViolation: true
  identificationType:
    or:
      apiKey:
        applicationLookup: 'registered'
      httpBasicAuth:
        applicationLookup: 'registered'

---
kind: Log
apiVersion: api.webmethods.io/beta
metadata:
  name: log_invocation
  version: 1.0
  namespace: dev
  tags:
    - log_invocation
spec:
  enabled: true
  logRequestHeaders: true # default value = false
  logResponseHeaders: true # default value = false
  logRequestPayload: true # default value = false
  logResponsePayload: true # default value = false
  compressPayloads: true # default value = false
  logGenerationFrequency: always
  destination:
    - email:
      - pradee@ibm.com        

---
kind: TransformRequest
apiVersion: api.webmethods.io/v1
metadata:
  name: request_processing_policy
  version: 1.0
  namespace: dev
  tags:
    - iden
spec:
  condition: (${request.headers.test} equals test1) or (${request.headers.test}
    notEquals ${request.payload.jsonPath[$.customer.name]})
  set:
      - key: ${request.headers.authorization}
        value: ${request.authorization.authHeader}
      - key: ${request.headers.h2}
        value: test-header-value
      - key: ${request.query.q2}
        value: ${request.path.name}
  setPayload:
      content-types:
        - application/xml: <test></test>
  remove:
      - ${request.query.q1}
      - ${request.path.mki}
  namespaces:
      - prefix: ps1
        URI: http://test.com
      - prefix: ps2
        URI: http://test2.com

---
kind: ValidateAPISpecification
apiVersion: api.webmethods.io/beta
metadata:
  namespace: dev
  name: validate_API_Specification_policy
  version: 1.0
spec:
  validate:
    - query
    - path
    - cookie
    - contentType
    - headers:
        condition: (${request.headers.test} equals test1) or (${request.headers.test})
    - schema:
        feature:
          - name: TOLERATE_DUPLICATES
            value: true
          - name: DISALLOW_DOCTYPE
            value: false
          - name: NAMESPACE_GROWTH
            value: false        