#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: ErrorProcessing
apiVersion: api.webmethods.io/beta
metadata:
  name: conditional_error_processing
  version: 1.0
  namespace: mon
spec:
  enabled: true
  condition: |
    "(${response.statusCode} equals 200) or
        (${request.headers.name} not-equals ${request.payload.jsonPath[$.pet.name]})"
  # other operators include Equals, Equals ignore case, Not equals, Not equals ignore case, Contains, Not Contains, Exists, Not Exists, IP Range, Greater Than, Lesser Than
  transformations:
    setStatus:
      - key: ${response.headers.h2}
        value: test4
      - key: ${request.query.q2}
        value: ${response.payload.jsonPath[$.pet.name]}
    remove:
      - ${request.query.q1}
      - ${request.path.mki}
    setPayload:
      content-types:
        - application/json: |
            {
                "petid":"1"
            }
        - application/xml: |
            <test></test>
        - text/plain: |
            "This is a plain content"
      default-content-type: application/json
      xsl:
        $path: format.xsl
    namespaces:
      - prefix: ps1
        URI: http://test.com
      - prefix: ps2
        URI: http://test2.com
    sendNativeError: true
  post-processing:
    xsl:
     $path: format.xsl