kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: webmPolicy
  namespace: Desktop_Invoke_Project
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: Desktop_Invoke_Project:invoke-webmPolicy:1.0
