kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: ConditionalRouting
  namespace: test
  version: '1.0'
  tags:
    - test
spec:
  default-endpoint:
    $ref: test:ep5:alpha
  conditional-endpoints:
    - endpoint:
        $ref: test:ep6:alpha
      condition: ''
    - endpoint:
        $ref: test:ep5:alpha
      condition: >-
        (${request.headers.test} notEquals
        ${request.payload.jsonPath[$.customer.name]})
