#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: policyseq
  version: 1.0
  namespace: mon
  tags:
    - seq
spec:
  transport:
    - $ref: mon:transport:alpha
  routing:
    - $ref: mon:routing:1.0
  monitoring:
    - $ref: mon:log_invocation:1.0
    - $ref: mon:monitor:1.0