kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: my-loadbalancer-routing-test_ui
  version: 1.0
  namespace: dev
  tags:
    - routing
    - route
    - policy
spec:
  loadbalance-endpoints:
    - $ref: dev:lb_endpoint_ui:1.0
      suspend-on-duration: 20s
    - $ref: dev:lb_endpoint2_ui:1.0
      suspend-on-duration: 40s
---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: lb_endpoint_ui
  version: 1.0
  namespace: dev
spec:
  url: ${pet_url_alias}  
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: DEFAULT_IS_KEYSTORE
    keyAlias: ssos
    trustStoreAlias: DEFAULT_IS_TRUSTSTORE
  serviceRegistryParameters:
    - name: ""
      value: ""
---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: lb_endpoint2_ui
  version: 1.0
  namespace: dev
spec:
  url: ${pet_url_alias2}  
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: DEFAULT_IS_KEYSTORE2
    keyAlias: ssos2
    trustStoreAlias: DEFAULT_IS_TRUSTSTORE2
  serviceRegistryParameters:
    - name: ""
      value: ""