kind: policySequence
apiVersion: api.webmethods.io/v1
metadata:
  name: dev_policies_ui_test
  version: 1.0
  namespace: dev
  tags:
    - dev_policies
spec:
  transport:
    - $ref: dev:enable_https_test:1.0
  iam:
    - $ref: dev:identify_and_authorize_test:1.0
  req-processing:
    - $ref: sample:req_datamasking_test:1.0
  monitoring:
   - $ref: beta:log_invocation_test:1.0
  routing:
    - $ref: dev:my-default-routing_test:1.0
    - $ref: sample:OutboundAlias_test:1.0
  error-handling:
    - $ref: sample:error_datamasking_test:1.0