kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: policy
  namespace: DeployFailure2
  version: '1.0'
  tags: []
spec:
  transport:
    - $ref: dev:transport_test:1.0
  routing:
    - $ref: dev_cors:routing:1.0
