kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: MyPetstoreApi
  namespace: dev
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: MyPetstoreApi-spec.json
  policy-sequence:
    - $ref: dev:PolicySequence:1.0
