kind: api
apiVersion: api.webmethods.io/v1
metadata:
  name: APIwCustomExtension_Automation_UI
  namespace: dev
  version: 1.0
  tags:
    - sample
  type: REST
spec:
  api-spec:
    $path: petstore.yaml
  policy-sequence: 
    - $ref: dev:dev_policies_ui:1.0
