kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-webmIAM
  namespace: Desktop_IAM_Project
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  endpoint:
    http:
      target:
        timeout: 30
        url: /api/v3
      verb: CUSTOM
  extensions:
    webm-gateway:
      apiVersion: api.ibm.com/v1
