kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint
  version: 1
  namespace: dev
spec:
  url: ${pet_url_alias}
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: DEFAULT_IS_KEYSTORE
    keyAlias: ssos
    trustStoreAlias: DEFAULT_IS_TRUSTSTORE
  serviceRegistryParameters:
    - name: ""
      value: ""
