
kind: CacheServiceResult
apiVersion: api.webmethods.io/beta
metadata:
  name: service_cache
  version: 1
  namespace: sample
  tags:
    - cache
    - service
    - result
    - monitoring
    - policy
spec:
  condition: (${request.headers.test} equals test1) and (${request.headers.test}
    equals test2) and (${request.query.test1} equals test1) and
    (${request.query.test2} equals test2)
  ttl: 4d
  enabled: true
  maxSize: 32kb