
kind: ValidateAPISpecification
apiVersion: api.webmethods.io/beta
metadata:
  namespace: beta
  name: validate_API_Specification_policy
  version: 1
spec:
  validate:
    - query
    - path
    - cookie
    - contentType
    - headers:
        condition: (${request.headers.test} equals test1) or (${request.headers.test})
    - schema:
        feature:
          - name: TOLERATE_DUPLICATES
            value: true
          - name: DISALLOW_DOCTYPE
            value: false
