kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: assetstore
  namespace: test_asset
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: assetstore-spec.yml
  policy-sequence:
    - $ref: test_asset:Policseq:1.0
