kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: Policseq
  namespace: test_asset
  version: '1.0'
  tags: []
spec:
  transport:
    - $ref: test:trns_test:1.0
  routing:
    - $ref: test:route_test:1.0
