kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: dynamicRoutingHeader_ui
  version: 1.0
  namespace: dev
spec:
  default-endpoint:
    $ref: dev:default_endpoint:1.0
    
  dynamic-endpoints:
  - useHeader:
      name: sample-header-name
      $ref: dev:dynamic_endpoint_header_ui:1.0

---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint_ui
  version: 1.0
  namespace: dev
spec:
  url: http://localhost:3000/
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""

---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: dynamic_endpoint_header_ui
  version: 1.0
  namespace: dev
spec:
  url: http://endpoint1/
  method: GET
  connectTimeout: 101
  readTimeout: 102
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""
