#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: Transport
apiVersion: api.webmethods.io/beta
metadata:
  name: transport_policy_ui
  namespace: dev
  version: alpha
  tags:
    - test
    - REST
spec: 
    protocol:
      - http