kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: webM
  namespace: test_new_VCS
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: test_new_VCS:invoke-webM:1.0
