kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/beta
metadata:
  name: IAM_vcs
  namespace: VCSProject_RCyaml
  version: '1.0'
  tags: []
spec:
  identificationType:
    or:
      apiKey:
        applicationLookup: registered
      httpBasicAuth:
        applicationLookup: registered
  triggerPolicyViolation: true
