kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: test_rcVCS
  namespace: VCSProject_RCyaml
  version: '1.0'
  tags: []
spec:
  api:
    $ref: 'VCSProject_RCyaml:JsonImport:1.0'
  environment:
    $ref: VCSProject_RCyaml:reenv:1.0
  request:
    - method: GET
      resource: /pet/12
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
      assertions:
        $ref: "dev_cors:basicassert:alpha"
