kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: routing
  version: 1.0
  namespace: mon
  tags:
    - routing
    - route
    - policy
spec:
  default-endpoint:
    $ref: mon:endpoint:alpha