kind: CacheServiceResult
apiVersion: api.webmethods.io/beta
metadata:
  name: service_cache
  version: 1.0
  namespace: mon
  tags:
    - cache
    - service
    - result
    - monitoring
    - policy
spec:
  condition: >-
    (${request.headers.test} equals test1) or (${request.query.test} equals
    test1})
  ttl: 6d
  enabled: true
  maxSize: 32kb