#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: policyseq
  version: 1
  namespace: iam_host_ip
  tags:
    - seq
spec:
  transport:
    - $ref: iam_host_ip:transport:alpha
  iam:
    - $ref: iam_host_ip:identify_and_authorize:1.0
  monitoring:
    - $ref: iam_host_ip:log_invocation:alpha
  routing:
    - $ref: iam_host_ip:routing:alpha