kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/beta
metadata:
  name: IAM
  namespace: iamvcs
  version: '1.0'
  tags:
    - test
spec:
  triggerPolicyViolation: true
  identificationType:
    or:
      apiKey:
        applicationLookup: global
      hostNameAddress:
        applicationLookup: global
