kind: CacheServiceResult
apiVersion: api.webmethods.io/beta
metadata:
  name: serviceresult
  namespace: devvcs
  version: '1.0'
  tags: []
spec:
  condition: >-
    (${request.headers.test} equals test1) or (${request.query.test} equals
    test1})
  ttl: 4d
  maxSize: 32kb
