kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: vcs_mar28
  namespace: test
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: vcs_mar28-spec.yml
  policy-sequence:
    - $ref: vcs:vcsPolicySeq_mar28:1.0