kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: test
  namespace: test
  version: '1.0'
  tags: []
spec:
  url: http://localhost:1000
  method: GET
  connectTimeout: 100
  readTimeout: 12
