kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: test_api
  namespace: test
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: test_api-spec.yml
  policy-sequence:
    - $ref: test:Policy_asset:1.0
