#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: routing
  version: 1.0
  namespace: dev
  tags:
    - routing
    - route
    - policy
spec:
  default-endpoint:
    $ref: dev:endpoint:1.0