kind: assertion
apiVersion: api.webmethods.io/beta
metadata:
  name: assert_swag
  namespace: Swagger_VCS
  version: '1.0'
  tags: []
spec:
  - name: validate response
    key: code
    action: equals
    value: 404
  - name: status
    key: status
    action: equals
    value: OK
