kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: swag_test
  namespace: Swagger_VCS
  version: '1.0'
  tags: []
spec:
  api:
    $ref: 'Swagger_VCS:Swagger json:1.0'
  environment:
    $ref: Swagger_VCS:Swag_env:1.0
  request:
    - method: GET
      resource: /pet/{petId}
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
      assertions:
        $ref: "Swagger_VCS:assert_swag:1.0"
