kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: transport
  namespace: Swagger_VCS
  version: '1.0'
  tags: []
spec:
  transport:
    - $ref: Swagger_VCS:tarnsport_test:1.0
  routing:
    - $ref: Swagger_VCS:swag_route:1.0
