#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint_ui
  version: 1.0
  namespace: dev
spec:
  url: https://localhost:4000/
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""
---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: conditional_endpoint1_ui
  version: 1.0
  namespace: dev
spec:
  url: http://endpoint1/
  method: GET
  connectTimeout: 101
  readTimeout: 102
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""

---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: conditional_endpoint2_ui
  version: 1.0
  namespace: dev
spec:
  url: http://endpoint2/
  method: GET
  connectTimeout: 201
  readTimeout: 202
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""
