#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: conditionalRouting_ui
  version: 1.0
  namespace: dev
  tags:
    - policySeq
    - test
spec:
  default-endpoint:
    $ref: dev:default_endpoint_ui:1.0  
  conditional-endpoints:
    - condition: "(${request.httpMethod} equals POST) or (${request.headers.name} notEquals ${request.payload.jsonPath[$.pet.name]})"
      endpoint:
        $ref: dev:conditional_endpoint1_ui:1.0
    - condition: "(${request.httpMethod} equals PUT) and (${request.headers.name} equals ${request.payload.jsonPath[$.pet.name]})"
      endpoint:
        $ref: dev:conditional_endpoint2_ui:1.0
