kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: webM
  namespace: vcs_new_nov25
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: vcs_new_nov25:invoke-webM:1.0
