kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: test-mock-Route
  namespace: dev
  version: ''
  tags: []
  description: ''
spec:
  mock-endpoint:
    enabled: true
    $ref: 'dev:test-mock-endpoint:'
