kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: APISpec
  namespace: NewVCSProject_Oct15
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./APISpec-spec.yml
  policy-sequence:
    - $ref: NewVCSProject_Oct15:PolicySeq:1.0
