kind: Transport
apiVersion: api.webmethods.io/v1
metadata:
  name: enable_https_test
  namespace: dev
  version: 1.0
spec: 
    protocol:
      - http
      - https
---
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: my-default-routing_test
  version: 1.0
  namespace: dev
  tags:
    - routing
    - route
    - policy
spec:
  default-endpoint:
    $ref: dev:default_endpoint_test:1.0
---
kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/v1
metadata:
  name: identify_and_authorize_test
  version: 1.0
  namespace: dev
  tags:
    - identify_and_authorize
spec:
  enabled: true
  triggerPolicyViolation: true
  identificationType:
    or:
      apiKey:
        applicationLookup: global
      httpBasicAuth:
        applicationLookup: registered
---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint_test
  version: 1.0
  namespace: dev
spec:
  url: ${pet_url_alias}  
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: DEFAULT_IS_KEYSTORE
    keyAlias: ssos
    trustStoreAlias: DEFAULT_IS_TRUSTSTORE
  serviceRegistryParameters:
    - name: ""
      value: ""
---
kind: Log
apiVersion: api.webmethods.io/beta
metadata:
  name: log_invocation_test
  version: 1.0
  namespace: beta
  tags:
    - log_invocation
spec:
  enabled: true
  logRequestHeaders: true # default value = false
  logResponseHeaders: true # default value = false
  logRequestPayload: true # default value = false
  logResponsePayload: true # default value = false
  compressPayloads: true # default value = false
  logGenerationFrequency: always
  destination:
    - self 
    - dev_portals:
      - devportal 1 #name of the portal instance in the gateway
    - email:
      - nas@sag.com
      - daso@sag.com
---
kind: DataMasking
apiVersion: api.webmethods.io/beta
metadata:
  name: error_datamasking_test
  version: 1.0
  namespace: sample
spec:
  enabled: false
  matchApplications:
    - 2d4e28ae-6209-44ec-ba4e-64c5fcc9b63d
    - 495d12eb-1712-46a0-9b23-142a3374e3a9
  transformations:
      set:
        - jPath: jpathexpression
          maskValue: jpathmask
        - xpath: xpathexpression
          namespaces:
            - prefix: ps1
              URI: http://test.com
            - prefix: ps2
              URI: http://test2.com
          maskValue: xpathmask
        - regex: regexexpression
          maskValue: regexmask
      remove:
        - ${request.query.authorization}
        - ${request.path}
  applyForTransactionLogging: true
  applyForPayload: true
---
kind: DataMasking
apiVersion: api.webmethods.io/beta
metadata:
  name: req_datamasking_test
  version: 1.0
  namespace: sample
spec:
  enabled: false
  matchApplications:
    - 2d4e28ae-6209-44ec-ba4e-64c5fcc9b63d
    - 495d12eb-1712-46a0-9b23-142a3374e3a9
  transformations:
      set:
        - jPath: jpathexpression1
          maskValue: jpathmask1
        - xpath: xpathexpression1
          namespaces:
            - prefix: ps1
              URI: http://test.com
            - prefix: ps2
              URI: http://test2.com
          maskValue: xpathmask1
        - regex: regexexpression1
          maskValue: regexmask1
      remove:
        - ${request.query.authorization}
        - ${request.path}
  applyForTransactionLogging: true
  applyForPayload: true
---
kind: OutboundAlias  
apiVersion: api.webmethods.io/beta
metadata:
  name: OutboundAlias_test
  version: 1.0
  namespace: sample  
spec:
  enabled: true
  alias: ${Test_Alias}