kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: apiFriday
  namespace: PublishTesting
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./apiFriday-spec.json
  policy-sequence:
    - $ref: PublishTesting:dpPublishFriday:1.0