kind: DataPowerAssembly
apiVersion: api.webmethods.io/beta
metadata:
  name: dpPublishFriday
  namespace: PublishTesting
  version: '1.0'
  tags: []
spec:
  x-ibm-configuration:
    gateway: datapower-api-gateway
    assembly:
      execute: []
      catch:
        - errors: []
          execute: []
