kind: GlobalPolicy
apiVersion: api.webmethods.io/beta
metadata:
  name: GlPolicy_apr5
  namespace: test
  version: '1.0'
  tags:
    - test
spec:
  filter-api-type:
    - REST
  filter-http-methods:
    - GET
    - PUT
  policy-sequence:
    - $ref: GlobalPolicy_API:test_policy:1.0
  filter-attributes: (${apiName} endsWith Sample) and (${apiVersion} equals 1.0)
