kind: DataMasking
apiVersion: api.webmethods.io/beta
metadata:
  name: DM_Req_Processing
  namespace: Swagger Project
  version: '1.0'
  tags:
    - test
spec:
  matchApplications:
    - app1
  applyForTransactionLogging: true
  transformations:
    remove: []
    setMask:
      - jPath: $.pet.name
        maskValue: '***'
      - xPath: $.customer.name
        maskValue: '***'
  applyForPayload: true
