kind: environment
apiVersion: api.webmethods.io/beta
metadata:
  name: Envtest
  namespace: Swagger Project
  version: '1.0'
  tags: []
spec:
  variables:
    - key: petId
      isSecret: false
      value: "13"
