kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: Swagger_ImportAPI
  namespace: Swagger Project
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: Swagger_ImportAPI-spec.yml
  policy-sequence:
    - $ref: Swagger Project:test_Policy:1.0

