kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: Test
  namespace: Swagger Project
  version: '1.0'
  tags: []
spec:
  api:
    $ref: "Swagger Project:SwaggerAPIVCS:1.0"
  environment:
    $ref: Swagger Project:Envtest:1.0
  request:
    - method: GET
      resource: /pet/{petId}
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
      assertions:
        $ref: "Swagger Project:assert_swagger:1.0"
