#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: Transport
apiVersion: api.webmethods.io/beta
metadata:
  name: transport
  namespace: iam_all
  version: alpha
spec: 
    protocol:
      - http