kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: conditional_endpoint1
  version: "1.0"
  namespace: dev
spec:
  url: http://endpoint1/
  method: GET
  connectTimeout: 101
  readTimeout: 102
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""