kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint
  version: 1
  namespace: dev
spec:
  url: https://localhost:4000/
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ''
    keyAlias: ''
    trustStoreAlias: ''
  serviceRegistryParameters:
    - name: ''
      value: ''
