kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: Inbound_Messaging_API
  namespace: api
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: Inbound_Messaging_API-spec.yml
  policy-sequence:
    - $ref: test:PolicySeq_message:1.0
