kind: Log
apiVersion: api.ibm.com/v1
metadata:
  name: LogPolicy
  namespace: Desktop_Log_Project
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  logRequestHeaders: true
  logRequestPayload: true
  logResponseHeaders: true
  logGenerationFrequency: onfailure
  destination:
    - email:
        - pradeepa@test.com
