kind: policySequence
apiVersion: api.webmethods.io/v1
metadata:
  name: dev_policies_ker
  version: 1.0
  namespace: dev
  tags:
    - dev_policies
spec:
  transport:
    - $ref: dev:enable_https_ker:1.0
  iam:
    - $ref: dev:identify_and_authorize_ker:1.0
  routing:
    - $ref: dev:my-default-routing_ker:1.0
    - $ref: sample:OutboundKerberosAuth_ker:1.0