#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: Sanity
  version: alpha
  tags:
    - functional
  namespace: iam_host_ip
spec:
  api:
    $ref: iam_host_ip:IAM_hostIPAPI_Import:1.0.0
  environment:
   $ref: iam_host_ip:env:1
  request:
    - method: GET
      resource: /pet/11
      headers:
        - key: Content-Type
          value: ${content-type}
        - key: Accept
          value: ${accept}
      auth:
        noauth: true
      settings:
        sslVerification: false
        encodeURL: true
      assertions:
         $ref: iam_host_ip:basicassert:1.23
