kind: MockEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: MockAPI-endpoint
  namespace: test
  version: alpha
  tags: []
  description: 'Mock API for updating pet details'
spec:
  paths:
    /pet:
      put:
        defaultResponse:
          '200':
            response:
              $ref: default:Mock-Response-dggrze:1.0
        conditionalResponse:
          - condition: $request.query.name != null
            statusCode: 200
            response:
              $ref: default:Mock-Response-dggrze:1.0