kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: MockAPI-Route
  namespace: test
  version: alpha
  tags: []
  description: ''
spec:
  mock-endpoint:
    enabled: true
    $ref: test:MockAPI-endpoint:alpha
