kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: MockAPI-PolicySeq
  namespace: test
  version: alpha
  tags: []
  description: ''
spec:
  routing:
    - $ref: test:MockAPI-Route:alpha
  transport:
    - $ref: dev:transport_test:1.0
  iam:
    - $ref: dev:IAM:1.0
