kind: Product
apiVersion: api.ibm.com/v1
metadata:
  name: DPv6_Product
  namespace: DPv6_Product_Weather
  version: '1.0'
  tags:
    - product
  description: ''
spec:
  apis:
    - $ref: DPv6_Product_Weather:WeatherApi:1.0
  plans:
    - $ref: DPv6_Product_Weather:DPv6_Plan:1.0
