kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: default_endpoint
  version: 1.0
  namespace: dev
spec:
  url: http://localhost:3000/
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""

---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: content_based_endpoint1
  version: 1.0
  namespace: dev
spec:
  url: http://endpoint1/
  method: GET
  connectTimeout: 101
  readTimeout: 102
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""

---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: content_based_endpoint2
  version: 1.0
  namespace: dev
spec:
  url: http://endpoint2/
  method: GET
  connectTimeout: 201
  readTimeout: 202
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""

---
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: content_based_endpoint3
  version: 1.0
  namespace: dev
spec:
  url: http://endpoint3/
  method: GET
  connectTimeout: 301
  readTimeout: 302
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    trustStoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""