kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: contentBasedRouting_ui
  version: 1.0
  namespace: dev
  tags:
    - test
    - content
spec:
  default-endpoint:
    $ref: dev:default_endpoint_ui:1.0
  content-based-endpoints:
    - payLoadIdentifier:
        xPath: 'some/xpath'
        namespaces:
        - prefix: 'ns1'
          URI: 'http://uri1'
        - prefix: 'ns2'
          URI: 'http://uri2'
      endpoint:
        $ref: dev:content_based_endpoint1_ui:1.0
    - payLoadIdentifier:
        jPath: 'some/jsonpath'
      endpoint:
        $ref: dev:content_based_endpoint2_ui:1.0
    - payLoadIdentifier:
        regex: 'some*regex'
      endpoint:
        $ref: dev:content_based_endpoint3_ui:1.0
