kind: StagedPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: webM
  namespace: VCSNew
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  routing:
    - $ref: VCSNew:invoke-webM:1.0
