kind: ValidateAPISpecification
apiVersion: api.webmethods.io/beta
metadata:
  name: Validatespec-Req
  namespace: CreateFlow
  version: '1.0'
  tags: []
spec:
  validate:
    - query
    - path
    - cookie
    - schema:
        feature:
          - name: GENERATE_SYNTHETIC_ANNOTATIONS
            value: true
    - headers: ' (${request.httpMethod} equals POST) or (${request.headers.name} notEquals ${request.payload.jsonPath[$.pet.name]})'
